---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 黎晓.
--- DateTime: 2025/12/19 15:10
---
--1.1优惠卷id
local voucherId = ARGV[1];
--1.2用户ID
local userId  = ARGV[2];

--订单id
local orderId = ARGV[3];

--Key
local stockKey = 'seckill:stock:' .. voucherId

local orderKey = 'seckill:order:' .. voucherId

--业务
--1.判断充足
if(tonumber(redis.call("get",stockKey))<=0) then
    return 1
end

--
if(redis.call("sismember",orderKey,userId) == 1)then
    return 2
end

--扣库存 下单 incrby stockKey -1
redis.call('incrby',stockKey,-1)

--下单 保存用户
redis.call('sadd',orderKey,userId)
--发送消息到队列中 xadd stream.orders * k1 v1 k2 v2
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId);

return 0